# path: .docker/docker-compose-postgres.base.yml

services:
  postgres-db:
    env_file:
      - ../.configs/.env.${NODE_ENV}
    image: ${ORGANIZATION}/codeblox-dev-postgres
    volumes:
      - test-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-db-volume:
